theme: jekyll-theme-cayman
# configuration
# fill in the course details
 
courseName: ITP 348 - Intro to Physical Computing

# small title that is at the top of every page
subtitle: Course Content

# baseurl is the same as the name of the repository
baseurl: /ITP348-Physical-Computing

# url where the required reading is available to download
docsUrl: "" 

# url where the student's grading info is kept
gradingUrl: "https://blackboard.usc.edu" 

# change only if you know what you are doing
collections:
  syllabus:
    output: true
  assignments:
    output: true
  lectures:
    output: true
  readings:
    output: true
defaults:
  - scope:
      path: ""
      type: syllabus
    values:
      layout: unit
  - scope:
      path: ""
      type: lectures
    values:
      layout: unit
  - scope:
      path: ""
      type: assignments
    values:
      layout: unit
  - scope:
      path: ""
      type: readings
    values:
      layout: unit
